//
//  ClipboardMonitor.swift
//  Clipy
//
//  Created by Ayman Omara on 07/08/2026.
//

import Foundation
import AppKit

/// Observes system pasteboard updates and notifies listeners when new items are copied.
final class ClipboardMonitor: ClipboardMonitoringProtocol {
    private let pasteboard: NSPasteboard
    private let exclusions: ExcludedAppsStore
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Rich representations above this size are dropped; the plain string is always kept.
    private let maxRichTextBytes = 1_000_000

    /// Markers apps (password managers, etc.) set on data that must not be recorded.
    /// See http://nspasteboard.org
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword")
    ]

    var onClipboardChanged: ((ClipboardCapture) -> Void)?

    init(pasteboard: NSPasteboard = .general, exclusions: ExcludedAppsStore = .shared) {
        self.pasteboard = pasteboard
        self.exclusions = exclusions
        self.lastChangeCount = pasteboard.changeCount
    }

    func startMonitoring() {
        stopMonitoring()

        // Poll the pasteboard changeCount periodically
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.checkPasteboard() }
        }
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }

        lastChangeCount = currentChangeCount

        if let types = pasteboard.types, !ignoredTypes.isDisjoint(with: types) { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        if exclusions.isExcluded(bundleID: sourceApp?.bundleIdentifier) { return }

        guard let content = readContent() else { return }
        onClipboardChanged?(ClipboardCapture(
            content: content,
            sourceAppName: sourceApp?.localizedName,
            sourceBundleID: sourceApp?.bundleIdentifier,
            changeCount: currentChangeCount
        ))
    }

    private func readContent() -> ClipboardCapture.Content? {
        // 1. File URLs (every file of a multi-selection)
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }

        // 2. Images; conversion to PNG happens later, off the main thread
        if pasteboard.canReadObject(forClasses: [NSImage.self], options: nil),
           let tiffData = pasteboard.data(forType: .tiff) {
            return .image(tiffData)
        }

        // 3. Plain text, with its rich representations when present
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let rtf = pasteboard.data(forType: .rtf).flatMap { $0.count <= maxRichTextBytes ? $0 : nil }
            let html = pasteboard.string(forType: .html).flatMap { $0.utf8.count <= maxRichTextBytes ? $0 : nil }
            return .text(text, rtf: rtf, html: html)
        }
        return nil
    }
}
